"""Generate the PulseNet ER diagram from database/schema.sql.

    python scripts/render_erd.py

database/schema.sql is the single source of truth for the diagram. This script
derives three files from it, and none of them is edited by hand:

    docs/db-diagram.mmd   the Mermaid erDiagram
    docs/db-diagram.md    the same Mermaid, between the GENERATED markers
    docs/db-diagram.png   the rendered picture (matplotlib), stamped with the
                          schema's sha256 so a test can tell when it is stale

Only what SQL cannot express lives here: where each table sits in the picture
(LAYOUT) and the wording of each relationship (LABELS).
backend/tests/unit/test_erd_docs.py fails when the files no longer match schema.sql.

Needs the backend requirements (it reuses split_sql from backend/migrate.py) plus
matplotlib, which is a documentation tool only: see docs/db-diagram.md.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path
from typing import List, NamedTuple, Tuple

ROOT        = Path(__file__).resolve().parent.parent
BACKEND_DIR = ROOT / "backend"
SCHEMA_SQL  = ROOT / "database" / "schema.sql"
MMD_FILE    = ROOT / "docs" / "db-diagram.mmd"
MD_FILE     = ROOT / "docs" / "db-diagram.md"
PNG_FILE    = ROOT / "docs" / "db-diagram.png"

# Found from the script's own location, so it runs from any working directory.
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))
from migrate import split_sql  # noqa: E402  (comment- and quote-aware SQL splitter)

# Where each table goes in the picture: columns left to right, each stacked top to bottom.
LAYOUT = [
    ["follows", "llm_usage"],
    ["sessions", "users", "reports"],
    ["likes", "posts", "comments"],
    ["posts_tags"],
    ["tags"],
]

# Relationship wording, keyed by (child table, foreign-key column). A foreign key
# that is missing here is labelled with its column name.
LABELS = {
    ("sessions", "user_id"): "has",
    ("posts", "author_id"): "authors",
    ("posts_tags", "post_id"): "tagged by",
    ("posts_tags", "tag_id"): "applied to",
    ("follows", "follower_id"): "is follower",
    ("follows", "following_id"): "is followed",
    ("likes", "user_id"): "likes",
    ("likes", "post_id"): "liked by",
    ("comments", "author_id"): "writes",
    ("comments", "post_id"): "commented on",
    ("comments", "parent_id"): "has replies",
    ("llm_usage", "user_id"): "uses",
    ("reports", "reporter_id"): "reports",
    ("reports", "resolved_by"): "resolves",
    ("reports", "post_id"): "reported in",
    ("reports", "comment_id"): "reported in",
}

PNG_DIGEST_KEY = "Schema-SHA256"
MD_BEGIN = "<!-- BEGIN GENERATED by scripts/render_erd.py from database/schema.sql: do not edit -->"
MD_END = "<!-- END GENERATED -->"
KEY_ORDER = ("PK", "FK", "UK")


class ErdError(Exception):
    """A problem the CLI reports as a one-line error (exit code 1)."""


class Column(NamedTuple):
    name: str
    type: str               # base type in lower case: int, varchar, enum, ...
    keys: Tuple[str, ...]   # some of KEY_ORDER, in that order
    nullable: bool


class ForeignKey(NamedTuple):
    columns: Tuple[str, ...]
    parent: str


class Table(NamedTuple):
    name: str
    columns: List[Column]
    foreign_keys: List[ForeignKey]


class Relationship(NamedTuple):
    parent: str
    child: str
    label: str
    optional: bool          # the foreign key is nullable: a child row may have no parent


# ─── schema.sql → tables ─────────────────────────────────────────────────────

_CREATE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?(\w+)`?\s*\((.*)\)", re.IGNORECASE | re.DOTALL
)
_COLUMN = re.compile(r"`?(\w+)`?\s+(\w+)(.*)", re.DOTALL)
_FOREIGN_KEY = re.compile(
    r"FOREIGN\s+KEY\s*(?:`?\w+`?\s*)?\(([^)]*)\)\s*REFERENCES\s+`?(\w+)`?", re.IGNORECASE
)
# "CONSTRAINT [name] PRIMARY KEY ..." is read as "PRIMARY KEY ...".
_CONSTRAINT_PREFIX = re.compile(
    r"^CONSTRAINT\s+(?:`?\w+`?\s+)?(?=PRIMARY|FOREIGN|UNIQUE|CHECK)", re.IGNORECASE
)
_NOT_COLUMNS = {"INDEX", "KEY", "CHECK", "FULLTEXT", "SPATIAL"}


def split_top_level(body):
    """Split a CREATE TABLE body on the commas outside parentheses and quotes, so
    ``ENUM('user', 'admin')`` or ``PRIMARY KEY (a, b)`` stays one item."""
    items, current, depth, quote = [], [], 0, None
    for ch in body:
        if quote:
            if ch == quote:
                quote = None
        elif ch in "'\"`":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            items.append("".join(current).strip())
            current = []
            continue
        current.append(ch)
    items.append("".join(current).strip())
    return [item for item in items if item]


def _listed_columns(item):
    """The names inside the first parentheses: ``PRIMARY KEY (a, `b`)`` -> ["a", "b"]."""
    match = re.search(r"\(([^)]*)\)", item)
    return re.findall(r"\w+", match.group(1)) if match else []


def parse_schema(sql_text):
    """Return the tables created in ``sql_text``, in file order. Statements other
    than CREATE TABLE (CREATE DATABASE, USE, CREATE INDEX) are skipped."""
    tables = []
    for statement in split_sql(sql_text):
        match = _CREATE_TABLE.match(statement)
        if not match:
            continue
        name, body = match.groups()
        definitions, primary, unique, foreign_keys = [], [], [], []
        for item in split_top_level(body):
            item = _CONSTRAINT_PREFIX.sub("", item)
            word = item.split(None, 1)[0].strip("`").upper()
            if word == "PRIMARY":
                primary += _listed_columns(item)
            elif word == "UNIQUE":
                unique += _listed_columns(item)
            elif word == "FOREIGN":
                fk = _FOREIGN_KEY.match(item)
                if not fk:
                    raise ErdError(f"{name}: cannot read {' '.join(item.split())!r}")
                foreign_keys.append(ForeignKey(tuple(re.findall(r"\w+", fk.group(1))), fk.group(2)))
            elif word not in _NOT_COLUMNS:
                column = _COLUMN.match(item)
                if not column:
                    raise ErdError(f"{name}: cannot read {' '.join(item.split())!r}")
                col_name, col_type, rest = column.groups()
                if re.search(r"\bPRIMARY\s+KEY\b", rest, re.IGNORECASE):
                    primary.append(col_name)
                if re.search(r"\bUNIQUE\b", rest, re.IGNORECASE):
                    unique.append(col_name)
                not_null = re.search(r"\bNOT\s+NULL\b", rest, re.IGNORECASE) is not None
                definitions.append((col_name, col_type.lower(), not_null))

        fk_columns = {col for fk in foreign_keys for col in fk.columns}
        known = {col_name for col_name, _type, _not_null in definitions}
        for listed in primary + unique + sorted(fk_columns):
            if listed not in known:
                raise ErdError(f"{name}: key on unknown column {listed!r}")

        columns = []
        for col_name, col_type, not_null in definitions:
            flags = {"PK": col_name in primary, "FK": col_name in fk_columns, "UK": col_name in unique}
            keys = tuple(key for key in KEY_ORDER if flags[key])
            # Primary-key columns are NOT NULL even when the definition does not say so.
            columns.append(Column(col_name, col_type, keys, not (not_null or flags["PK"])))
        tables.append(Table(name, columns, foreign_keys))

    if not tables:
        raise ErdError("no CREATE TABLE statements found")
    return tables


def relationships(tables):
    """One relationship per foreign key, in schema order."""
    found = []
    for table in tables:
        nullable = {column.name: column.nullable for column in table.columns}
        for fk in table.foreign_keys:
            label = LABELS.get((table.name, fk.columns[0]), fk.columns[0])
            optional = any(nullable[col] for col in fk.columns)
            found.append(Relationship(fk.parent, table.name, label, optional))
    return found


def join_tables(tables):
    """Tables whose primary key is two or more foreign-key columns: the M:N links."""
    joins = []
    for table in tables:
        pk = [column for column in table.columns if "PK" in column.keys]
        if len(pk) >= 2 and all("FK" in column.keys for column in pk):
            joins.append(table.name)
    return joins


def check_layout(tables):
    """Every table needs a place in LAYOUT, and LAYOUT may name only real tables."""
    placed = [name for column in LAYOUT for name in column]
    names = [table.name for table in tables]
    problems = []
    missing = [name for name in names if name not in placed]
    if missing:
        problems.append(f"no place in LAYOUT for {', '.join(missing)}")
    unknown = [name for name in placed if name not in names]
    if unknown:
        problems.append(f"LAYOUT names tables that schema.sql lacks: {', '.join(unknown)}")
    if problems:
        raise ErdError("; ".join(problems) + " (edit LAYOUT in scripts/render_erd.py)")


def schema_digest(sql_text):
    """sha256 of schema.sql with LF line endings (a CRLF checkout hashes the same)."""
    return hashlib.sha256(sql_text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


# ─── tables → Mermaid ────────────────────────────────────────────────────────

def mermaid(tables):
    """The schema as a Mermaid erDiagram, ending with a newline."""
    lines = ["erDiagram"]
    rels = relationships(tables)
    if rels:
        parent_w = max(len(rel.parent) for rel in rels)
        child_w = max(len(rel.child) for rel in rels)
        for rel in rels:
            parent_end = "|o" if rel.optional else "||"
            lines.append(
                f'    {rel.parent:<{parent_w}} {parent_end}--o{{ {rel.child:<{child_w}} : "{rel.label}"'
            )
    for table in tables:
        type_w = max(len(column.type) for column in table.columns)
        name_w = max(len(column.name) for column in table.columns)
        lines += ["", f"    {table.name} {{"]
        for column in table.columns:
            row = f"        {column.type:<{type_w}} {column.name:<{name_w}} {', '.join(column.keys)}"
            lines.append(row.rstrip())
        lines.append("    }")
    return "\n".join(lines) + "\n"


def update_markdown(md_text, mermaid_text):
    """``md_text`` with the block between MD_BEGIN and MD_END replaced by the diagram."""
    start, end = md_text.find(MD_BEGIN), md_text.find(MD_END)
    if start == -1 or end < start:
        raise ErdError(f"{MD_FILE.name} lacks the GENERATED markers ({MD_BEGIN} ... {MD_END})")
    block = f"{MD_BEGIN}\n```mermaid\n{mermaid_text}```\n"
    return md_text[:start] + block + md_text[end:]


# ─── tables → PNG (matplotlib is imported only here) ─────────────────────────

DPI = 150
PT = DPI / 72                    # pixels per point
MARGIN, TITLE_H, LEGEND_H = 80, 110, 90
COL_GAP, ROW_GAP = 170, 90       # between layout columns / stacked tables
HEADER_H, ROW_H, BODY_PAD, TEXT_PAD = 62, 44, 14, 18
MONO_EM, BOLD_EM, ITALIC_EM = 0.60, 0.68, 0.56   # rough average glyph widths (DejaVu), in ems
FONT = {"title": 17, "header": 12, "column": 10, "key": 8.5, "label": 9, "card": 11, "legend": 10}
COLOR = {
    "header": "#2f6f9f", "border": "#333333", "key": "#b35a00",
    "line": "#555555", "label": "#333333", "text": "#000000",
}


def _load_pyplot():
    try:
        import matplotlib
    except ImportError:
        raise ErdError(
            "matplotlib is not installed: pip install matplotlib (see docs/db-diagram.md)"
        ) from None
    matplotlib.use("Agg")
    # matplotlib ships DejaVu, so the picture does not depend on the fonts of the machine.
    matplotlib.rcParams["font.family"] = "DejaVu Sans"
    from matplotlib import pyplot
    return pyplot


def _box_size(table):
    names_w = max(len(column.name) for column in table.columns) * FONT["column"] * PT * MONO_EM
    keys_w = max(len(", ".join(column.keys)) for column in table.columns) * FONT["key"] * PT * BOLD_EM
    title_w = len(table.name) * FONT["header"] * PT * BOLD_EM
    width = max(names_w + keys_w + 2 * TEXT_PAD + 40, title_w + 2 * TEXT_PAD, 260)
    height = HEADER_H + 2 * BODY_PAD + ROW_H * len(table.columns)
    return width, height


def layout_boxes(tables):
    """``({table: (x, y, width, height)}, figure width, figure height)`` in pixels,
    with y growing downwards. Each LAYOUT column is centred on the tallest one."""
    check_layout(tables)
    sizes = {table.name: _box_size(table) for table in tables}
    heights = [sum(sizes[name][1] for name in col) + ROW_GAP * (len(col) - 1) for col in LAYOUT]
    tallest = max(heights)
    boxes, x = {}, MARGIN
    for col, col_h in zip(LAYOUT, heights):
        y = TITLE_H + (tallest - col_h) / 2
        for name in col:
            width, height = sizes[name]
            boxes[name] = (x, y, width, height)
            y += height + ROW_GAP
        x += max(sizes[name][0] for name in col) + COL_GAP
    return boxes, x - COL_GAP + MARGIN, TITLE_H + tallest + LEGEND_H


def _centre(box):
    x, y, width, height = box
    return x + width / 2, y + height / 2


def _edge_point(box, toward):
    """Where the line from the centre of ``box`` toward ``toward`` crosses its border."""
    (cx, cy), (_x, _y, width, height) = _centre(box), box
    dx, dy = toward[0] - cx, toward[1] - cy
    scales = [half / abs(d) for half, d in ((width / 2, dx), (height / 2, dy)) if d]
    scale = min(scales) if scales else 0
    return cx + dx * scale, cy + dy * scale


def _draw_table(ax, table, box):
    from matplotlib.patches import Rectangle

    x, y, width, height = box
    ax.add_patch(Rectangle((x, y), width, height, facecolor="white",
                           edgecolor=COLOR["border"], linewidth=1.5, zorder=2))
    ax.add_patch(Rectangle((x, y), width, HEADER_H, facecolor=COLOR["header"],
                           edgecolor=COLOR["border"], linewidth=1.5, zorder=3))
    ax.text(x + width / 2, y + HEADER_H / 2, table.name, ha="center", va="center",
            color="white", fontsize=FONT["header"], fontweight="bold", zorder=4)
    row_y = y + HEADER_H + BODY_PAD + ROW_H / 2
    for column in table.columns:
        ax.text(x + TEXT_PAD, row_y, column.name, ha="left", va="center", family="DejaVu Sans Mono",
                fontsize=FONT["column"], color=COLOR["text"], zorder=4)
        if column.keys:
            ax.text(x + width - TEXT_PAD, row_y, ", ".join(column.keys), ha="right", va="center",
                    fontsize=FONT["key"], fontweight="bold", color=COLOR["key"], zorder=4)
        row_y += ROW_H


SELF_LOOP_REACH = 46             # how far a table's loop to itself sticks out to the right


def _self_loop_points(box):
    """The loop of a foreign key to its own table (comments.parent_id): out of the
    right side of ``box``, across and back in, as four (x, y) points."""
    x, y, width, height = box
    right, top, bottom = x + width, y + height * 0.4, y + height * 0.6
    return [(right, top), (right + SELF_LOOP_REACH, top),
            (right + SELF_LOOP_REACH, bottom), (right, bottom)]


def _draw_self_loop(ax, rels, box):
    # A straight line from the box to itself would have no length: the cardinalities
    # and the label would land in the middle of the table.
    points = _self_loop_points(box)
    ax.plot([p[0] for p in points], [p[1] for p in points], color=COLOR["line"], linewidth=1.6, zorder=1)
    card = {"ha": "center", "va": "center", "fontsize": FONT["card"], "fontweight": "bold", "zorder": 5}
    (out_x, top), (loop_x, _), _, (_, bottom) = points
    ax.text(out_x + 24, top - 14, "0..1" if any(rel.optional for rel in rels) else "1", **card)
    ax.text(out_x + 24, bottom + 14, "*", **card)
    ax.text(loop_x + 8, (top + bottom) / 2, " / ".join(rel.label for rel in rels), ha="left",
            va="center", fontsize=FONT["label"], style="italic", color=COLOR["label"], zorder=5,
            bbox={"boxstyle": "round,pad=0.2", "facecolor": "white", "edgecolor": "none"})


def _draw_relationships(ax, tables, boxes):
    # Several foreign keys from one table to the same parent (follows -> users) share a line.
    grouped = {}
    for rel in relationships(tables):
        grouped.setdefault((rel.parent, rel.child), []).append(rel)
    for (parent, child), rels in grouped.items():
        if parent == child:
            _draw_self_loop(ax, rels, boxes[parent])
            continue
        start = _edge_point(boxes[parent], _centre(boxes[child]))
        end = _edge_point(boxes[child], _centre(boxes[parent]))
        ax.plot([start[0], end[0]], [start[1], end[1]], color=COLOR["line"], linewidth=1.6, zorder=1)

        length = max(((end[0] - start[0]) ** 2 + (end[1] - start[1]) ** 2) ** 0.5, 1)
        along = ((end[0] - start[0]) / length, (end[1] - start[1]) / length)
        side = (along[1], -along[0])            # perpendicular to the line...
        if side[1] > 0 or (side[1] == 0 and side[0] < 0):
            side = (-side[0], -side[1])         # ...always toward its upper (or right) side

        def at(point, forward, sideways):
            return (point[0] + along[0] * forward + side[0] * sideways,
                    point[1] + along[1] * forward + side[1] * sideways)

        card = {"ha": "center", "va": "center", "fontsize": FONT["card"], "fontweight": "bold", "zorder": 5}
        ax.text(*at(start, 22, 14), "0..1" if any(rel.optional for rel in rels) else "1", **card)
        ax.text(*at(end, -22, 14), "*", **card)

        label = " / ".join(rel.label for rel in rels)
        if abs(along[0]) < 0.5:
            offset = 0      # a steep line: the label sits on it, hiding that piece of it
        else:               # beside the line, just far enough for its box to clear it
            half_w = len(label) * FONT["label"] * PT * ITALIC_EM / 2
            half_h = FONT["label"] * PT * 0.6
            offset = half_w * abs(side[0]) + half_h * abs(side[1]) + 8
        mid = ((start[0] + end[0]) / 2, (start[1] + end[1]) / 2)
        ax.text(*at(mid, 0, offset), label, ha="center", va="center",
                fontsize=FONT["label"], style="italic", color=COLOR["label"], zorder=5,
                bbox={"boxstyle": "round,pad=0.2", "facecolor": "white", "edgecolor": "none"})


def render_png(pyplot, tables, digest, path):
    """Draw the diagram to ``path``, with ``digest`` in the PNG metadata."""
    boxes, width, height = layout_boxes(tables)
    fig = pyplot.figure(figsize=(width / DPI, height / DPI), dpi=DPI)
    ax = fig.add_axes((0, 0, 1, 1))
    ax.set_xlim(0, width)
    ax.set_ylim(height, 0)
    ax.axis("off")

    ax.text(width / 2, TITLE_H / 2, "PulseNet — Database Schema (ERD)", ha="center",
            va="center", fontsize=FONT["title"], fontweight="bold")
    _draw_relationships(ax, tables, boxes)
    for table in tables:
        _draw_table(ax, table, boxes[table.name])

    legend = "Legend:   PK primary key    FK foreign key    UK unique    |    1 — *  one-to-many"
    joins = join_tables(tables)
    if joins:
        legend += f"    |    M:N via join tables ({', '.join(joins)})"
    ax.text(width / 2, height - LEGEND_H / 2, legend, ha="center", va="center",
            fontsize=FONT["legend"], color=COLOR["label"])

    fig.savefig(path, dpi=DPI, facecolor="white", metadata={PNG_DIGEST_KEY: digest})
    pyplot.close(fig)


# ─── CLI ─────────────────────────────────────────────────────────────────────

def _write_text(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main(argv=None):
    argparse.ArgumentParser(
        prog="render_erd.py",
        description="Regenerate docs/db-diagram.{png,mmd,md} from database/schema.sql.",
    ).parse_args(argv)
    try:
        schema = SCHEMA_SQL.read_text(encoding="utf-8")
        tables = parse_schema(schema)
        check_layout(tables)
        mermaid_text = mermaid(tables)
        md_text = update_markdown(MD_FILE.read_text(encoding="utf-8"), mermaid_text)
        pyplot = _load_pyplot()      # fails before anything is written
        render_png(pyplot, tables, schema_digest(schema), PNG_FILE)
        _write_text(MMD_FILE, mermaid_text)
        _write_text(MD_FILE, md_text)
    except ErdError as exc:
        print(f"render_erd: {exc}", file=sys.stderr)
        return 1
    written = ", ".join(str(path.relative_to(ROOT)) for path in (PNG_FILE, MMD_FILE, MD_FILE))
    print(f"render_erd: {len(tables)} tables from database/schema.sql -> {written}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
